steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform'
    args: ['-chdir=terraform', 'terraform', 'init']
  - id: 'terraform apply'
    name: 'hashicorp/terraform'
    args: ['-chdir=terraform', 'terraform', 'apply', '--auto-approve']