# JOB STEPS
steps:
  - id: "tf init"
    name: "hashicorp/terraform"
    dir: "terraform"
    args:
      - -x
      - -c
      - terraform init

  - id: "tf apply"
    name: "hashicorp/terraform"
    dir: "terraform"
    args:
      - -x
      - -c
      - terraform apply 