# JOB STEPS
steps:
  - id: "tf init"
    name: "hashicorp/terraform:latest"
    dir: "terraform"
    entrypoint: 'sh'
    args:
      - -x
      - -c
      - terraform init

  - id: "tf apply"
    name: "hashicorp/terraform:latest"
    dir: "terraform"
    entrypoint: 'sh'
    args:
      - -x
      - -c
      - terraform apply 