# JOB STEPS
steps:
  - id: "tf init"
    name: "terraform init"
    dir: "terraform"
    args:
      - -x
      - -c
      - terraform init

  - id: "tf apply"
    name: $_BUILDER_FULL_NAME
    dir: "terraform"
    args:
      - -x
      - -c
      - terraform apply 